---
- block:
  - name: install librenms
    ansible.builtin.script: "install_librenms.sh '{{ librenms_db_user }}' '{{ librenms_db_password }}' '{{ librenms_snmpd_community }}'"
    args:
      creates: "/opt/librenms"
  - name: setup mysql config
    ansible.builtin.copy:
      src: "99-custom.cnf"
      dest: "/etc/mysql/mariadb.conf.d/99-custom.cnf"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: install php timezone
    ansible.builtin.template:
      src: "timezone.ini.j2"
      dest: "/etc/php/7.3/mods-available/timezone.ini"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: setup php fpm and cli timezone
    ansible.builtin.file:
      src: "/etc/php/7.3/mods-available/timezone.ini"
      dest: "/etc/php/7.3/{{ item }}/conf.d/99-timezone.ini"
      owner: "root"
      group: "root"
      state: "link"
    loop:
      - fpm
      - cli
  - name: reload php fpm service
    ansible.builtin.systemd:
      name: "php7.3-fpm"
      state: "restarted"
  - name: remove default nginx config
    ansible.builtin.file:
      path: /etc/nginx/sites-enabled/default
      state: absent
  - name: add librenms nginx config file
    ansible.builtin.copy:
      src: "librenms_nginx"
      dest: "/etc/nginx/sites-available/librenms"
      owner: "root"
      group: "root"
      mode: "0644"
  - name: activate librenms nginx config
    ansible.builtin.file:
      src: "/etc/nginx/sites-available/librenms"
      dest: "/etc/nginx/sites-enabled/librenms"
      owner: "root"
      group: "root"
      state: "link"
  - name: restart nginx
    ansible.builtin.systemd:
      name: "nginx"
      state: "restarted"
  tags:
    - librenms
